version: "3"

services:

  price_generator:
    image: price_generator:latest
    environment:
      REDIS_ADDR: "redis:6379"

  price_service:
    image: price_service:latest
    environment:
      REDIS_ADDR: "redis:6379"
    ports:
      - "8082:8082"
  position_service:
    image: position_service:latest
    ports:
      - "8083:8083"
    depends_on:
      - price_service
  client:
    image: client
    depends_on:
      - price_service
      - position_service

  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "egormelnikovdb"
      POSTGRES_USER: "egormelnikov"
      POSTGRES_PASSWORD: "54236305"
    ports:
      - "5444:5432"